### ISSUE TITLE
Add type definition

### ISSUE THREAD

**Issue by ajayesivan** [ajayesivan/react-native-remix-icon#12]

**Comment by adijha** [comment]
Please, we need this very strongly

**Comment by Yawmm** [comment]
Any updates on this?

**Comment by adijha** [comment]
@Yawmm  I'll be picking this up
Need more time, I can raise PR at around April last week

**Comment by Yawmm** [comment]
Alright awesome, really love the library!

**Comment by HelixHEX** [comment]
Any update on this?

**Comment by ajayesivan** [comment]
@HelixHEX Will be releasing a new version later this week with type definitions.

**Comment by AntoineKM** [comment]
Hey @ajayesivan & @HelixHEX any news about the new version with typedefs ? 😇

**Comment by AntoineKM** [comment]
temporary support with:
```typescript
// remixicon.d.ts

declare module "react-native-remix-icon" {
  declare const RemixIcon: React.FC<RemixIconProps>;

  declare interface RemixIconProps {
    name: string;
    size?: number | string;
    color?: string;
    [key: string]: any;
  }

  export default RemixIcon;
}
```
