### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by SEBIIWA** [ajayesivan/react-native-remix-icon#15]
Icons like 
* setting
* search
* and bookmarks
are missing while others like file search and such are available

**Comment by ajayesivan** [comment]
@nyuuke What happened, why did you close this issue?

**Comment by bobbyrinaldy** [comment]
@ajayesivan Hi, looks like some of icons are missing, such as Megaphone-*

**Comment by ajayesivan** [comment]
@bobbyrinaldy I will check it this weekend.

**Comment by bobbyrinaldy** [comment]
Hi @ajayesivan , when do you think the update is available on NPM ?
